name: gatekeeper
description: "A lightweight, real-time visitor management system for gated communities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^3.8.1

  # Firebase Authentication
  firebase_auth: ^5.3.4

  # Google Sign In
  google_sign_in: ^6.2.1

  # Cloud Firestore
  cloud_firestore: ^5.6.0

  # Firebase Cloud Messaging (Push Notifications)
  firebase_messaging: ^15.1.6

  # Local Notifications
  flutter_local_notifications: ^18.0.1

  # State Management
  provider: ^6.1.2

  # Phone Number Input
  intl_phone_field: ^3.2.0

  # OTP Input Field
  pinput: ^5.0.1

  # Loading Indicators
  flutter_spinkit: ^5.2.1

  # Date/Time Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets folder for images
  # assets:
  #   - assets/images/